config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get "/new-owner", to: "users#new_owner", as: :new_owner
  get "/new-sitter", to: "users#new_sitter", as: :new_sitter
  get "/user-sign-in", to: "users#sign_in"
  post "/new-owner", to: "users#owner_create"
  post "/new-sitter", to: "users#sitter_create"
  get "/account/:id", to: "users#account", as: :account
  get "/sitter-profile/:id", to: "users#sitter_profile"
  get "/sitter-profile/:id/edit", to:"users#edit_sitter"
  post "/edit-sitter/:id", to:"users#update_sitter_profile"
  get "/sitters", to: "users#sitters"
  post "/select-sitter/:id", to: "users#select_sitter"

  get "/new-client", to: "users#new_client"
  post "/new-client", to: "users#new_client"

  post "/sign-in", to: "sessions#sign_in", as: :sign_in
  get "/sign-out", to: "sessions#sign_out", as: :sign_out

  get "/new-pet", to: "pets#new", as: :new_pet
  post "/new-pet", to: "pets#create"
  get "/report/:id", to: "pets#report", as: :report
  post "/report/:id", to: "reports#create_report"

  get "/images", to: "instagram#show"

  get "/pet/:id", to: "pets#show"

  get "yappytrailsclub/about", to: "reports#about", as: :about

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :owner, class_name: "User"
  has_many :reports
  has_many :sitter_records
  has_many :images
  mount_uploader :picture, ImageUploader
  validates :picture, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
  end

  def report
    @pet = Pet.find_by(id: params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
    # @pet.picture = params[:pet][:picture]
    if @pet.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/new-owner", notice: @pet.errors
    end

  end



  def show
    @pet = Pet.find_by(id: params[:id])

    @sitter_ids = []
    @images = []
    @pet.reports.each do |i|
      i.images.each do |p|
        @images << p.image_url
      end
    end
    @pet.sitter_records.each do |r|
      @sitter_ids << r.sitter_id
    end
    render :json=> {
      pet: @pet,
      owner: @pet.owner,
      reports: @pet.reports.as_json(include: {images: {methods: :square_image} } )
      }
  end

  def profile
    @pet = Pet.find_by(id: params[:id])
  end


  private

  def pet_params
    params.require(:pet).permit(:picture, :owner_id, :name, :breed, :color, :sitter_id)
  end


end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/new.html.erb
<div class="new-pet">

  <h1>Create a Pet Profile!</h1>

  <%= form_tag "/new-pet", multipart: true do %>
    <input type="hidden" name="pet[owner_id]" value="<%= current_user.id %>" />
    <%= text_field_tag "pet[name]", nil, placeholder: "name", class: "name", :required => true  %>
    <br>
    <%= text_field_tag "pet[breed]", nil, placeholder: "breed", class: "breed", :required => true  %>
    <br>
    <%= text_field_tag "pet[color]", nil, placeholder: "color", class: "color", :required => true  %>
    <br>
    <%= label_tag "Upload Photo" %>
    <%= file_field_tag "pet[picture]" %>
    <%= submit_tag "Add Pet" %>
  <%end%>

</div>

app/views/pets/report.html.erb
<div class="new-pet">

  <h1>Report Card for <%= @pet.name %> </h1>

  <%= form_tag "/report/#{@pet.id}", multipart: true do %>
    <input type="hidden" name="report[sitter_id]" value="<%= current_user.id %>" />
    <input type="hidden" name="report[pet_id]" value="<%= @pet.id %>" />
    <input type="hidden" name="report[owner_id]" value="<%= @pet.owner.id %>" />
    <br>
    <%= text_field_tag "report[activity]", nil, placeholder: "activities", class: "activities", :required => true  %>
    <br>
    <%= text_field_tag "report[emotion]", nil, placeholder: "mood", class: "mood", :required => true  %>
    <br>
    <%= label_tag "Upload Image" %>
    <%= file_field_tag "image[image_url]", :required => true  %>
    <br>
    <%= label_tag "Upload Image(optional)" %>
    <%= file_field_tag "image[image_url]" %>
    <br>
    <%= label_tag "Upload Image(optional)" %>
    <%= file_field_tag "image[image_url]" %>
    <br>
    <%= submit_tag "Send Report" %>
  <%end%>

</div>

app/views/pets/show.html.erb
<h1>Dashboard for <%= @pet.name %> </h1>

<% if @pet.sitter_records.count > 0 %>
  <% if @sitter_ids.include?(@current_user.id) %>
    <h4><%= link_to "Create Report", report_path %></h4>
    <% end %>
<% end %>


  <h2>Reports</h2>
  <% @pet.reports.each do |r| %>
  <div class= "reportcard">
    <div class= "time">
      <%= r.created_at.strftime("%A %b %e %Y") %>
    </div>
    <div class= "activity">
      Activity:<%= r.activity %>
    </div>
    <div class= "emotion">
      Mood:<%= r.emotion %>
    </div>
    <div class= "images">
      <% r.images.each do |i| %>
      <div class="fb-share-button" data-href="<% i.image_url.url %>" data-layout="link"></div>
        <%= image_tag i.image_url.url(:image) %>
      <% end  %>
    </div>
  </div>
  <% end  %>