config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get "/new-owner", to: "users#new_owner", as: :new_owner
  get "/new-sitter", to: "users#new_sitter", as: :new_sitter
  get "/user-sign-in", to: "users#sign_in"
  post "/new-owner", to: "users#owner_create"
  post "/new-sitter", to: "users#sitter_create"
  get "/account/:id", to: "users#account", as: :account
  get "/sitter-profile/:id", to: "users#sitter_profile"
  get "/sitter-profile/:id/edit", to:"users#edit_sitter"
  post "/edit-sitter/:id", to:"users#update_sitter_profile"
  get "/sitters", to: "users#sitters"
  post "/select-sitter/:id", to: "users#select_sitter"

  get "/new-client", to: "users#new_client"
  post "/new-client", to: "users#new_client"

  post "/sign-in", to: "sessions#sign_in", as: :sign_in
  get "/sign-out", to: "sessions#sign_out", as: :sign_out

  get "/new-pet", to: "pets#new", as: :new_pet
  post "/new-pet", to: "pets#create"
  get "/report/:id", to: "pets#report", as: :report
  post "/report/:id", to: "reports#create_report"

  get "/images", to: "instagram#show"

  get "/pet/:id", to: "pets#show"

  get "yappytrailsclub/about", to: "reports#about", as: :about

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  has_many :roles
  has_secure_password validations: false
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :sitter_records
  validates :password, confirmation: true, presence: true, if: :needs_password?
  validates :username, presence: true, if: :registered
  mount_uploader :picture, ImageUploader




  def user_roles
    roles=[]
    self.roles.each do |r|
      roles << r.role
    end
    return roles
  end

  def registered
    if self.roles.where("role=? or role=?", "sitter", "owner").count > 0
      true
    end
  end

  def needs_password?
    if new_record? && registered
      true
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :bio

  def index

  end

  def new_client
    @user = User.new(user_params)
    if @user.save
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      @pet =  Pet.new(name: params[:pet][:name], owner_id: @user.id)
      @pet.save
      @sitter_record = SitterRecord.new(pet_id: @pet.id, owner_id: @user_id, sitter_id: @current_user.id)
      @sitter_record.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/new-owner", notice: "New client did not save"
    end
  end

  def owner_create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      redirect_to "/new-pet"
    else
      redirect_to "/new-owner", notice: "Username or email not complete, or passwords do not match."
    end
  end

  def sitter_create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      redirect_to "/sitter-profile/#{@user.id}"
    else
      redirect_to "/new-sitter", notice: "Username or email not complete, or passwords do not match."
    end
  end

  def new_sitter
  end

  def account
    @pets = Pet.where(owner_id: @current_user.id)
    @clients = SitterRecord.where(sitter_id: @current_user.id)
    @sitter_records = SitterRecord.where(owner_id: @current_user.id)
    @my_sitters = []
    @sitter_records.each do |s|
      @my_sitters << s unless @my_sitters.include?(s.sitter_id)
    end
  end

  def sitter_profile
    @sitter = User.find(params[:id])
  end

  def update_sitter_profile
    @update = User.find(params[:id])
    @update.bio = params[:user][:bio]
    @update.picture = params[:user][:picture]
    @update.save
    if @update.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/sitter-profile/#{@current_user.id}/edit", notice: "Update not saved."
    end
  end

  def edit_sitter
    @sitter = User.find(params[:id])
  end

  def sitters
    @sitters = Role.where(role: "sitter")
  end

  def select_sitter
    @pets = Pet.where(owner_id: @current_user.id)
    @sitter = User.find(params[:id])
    @pets.each do |p|
      SitterRecord.create(sitter_id: @sitter.id, owner_id: @current_user.id, pet_id: p.id)
    end
    redirect_to "/account/#{@current_user.id}"
  end



  private

  def user_params
    params.require(:user).permit(:bio, :email, :password, :phone, :username, :name, :role, :current_city, :password_confirmation, :picture)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new_user_form.html.erb
  <%= email_field_tag "user[email]", nil, placeholder: "email", class: "email", :required => true  %>
  <br>
  <%= text_field_tag "user[phone]", nil, placeholder: "phone(optional to receive SMS)", class: "phone" %>
  <br>
  <%= text_field_tag "user[name]", nil, placeholder: "name", class: "name", :required => true  %>
  <br>
  <%= text_field_tag "user[username]", nil, placeholder: "username", class: "username", :required => true  %>
  <br>
  <%= password_field_tag "user[password]", nil, placeholder: "password", class: "password", :required => true  %>
  <br>
  <%= password_field_tag "user[password_confirmation]", nil, placeholder: "password confirmation", class: "password_confirmation", :required => true %>
  <br>
  <%= text_field_tag "user[current_city]", nil, placeholder: "current city", class: "current_city", :required => true  %>
  <br>
  <%= submit_tag "Sign Up" %>

app/views/users/account.html.erb
<h1 class="user-dash"><%= current_user.name %>'s Yappy Trails</h1>

<% if !current_user.user_roles.include?("sitter")%>
  <!-- <a>I am also a sitter</a> -->
<% end %>

<% if !current_user.user_roles.include?("owner")%>
  <!-- <a>I am also a pet owner</a> -->
  <!-- <%= link_to "Edit Profile", "/sitter-profile/#{@current_user.id}/edit" %> -->
<% end %>

<% if current_user.user_roles.include?("sitter")%>


<div class="side-image">
  <div class="images-wrapper">
    <h1>My Clients</h1>
    <a class="client">Add new client</a>
    <div class="showit" style="display: none">
      <%= form_tag "/new-client" do %>
        <input type="hidden" name="role[role]" value="unregistered"/>
        <%= text_field_tag "user[name]", nil, placeholder: "owner name", class: "name", :required => true %>
        <%= email_field_tag "user[email]", nil, placeholder: "owner email", class: "email", :required => true %>
        <%= text_field_tag "user[phone]", nil, placeholder: "owner phone", class: "phone", :required => true %>
        <%= text_field_tag "pet[name]", nil, placeholder: "pet name", class: "pet", :required => true %>
        <%= text_field_tag "pet[breed]", nil, placeholder: "pet breed", class: "pet breed", :required => true %>
        <%= text_field_tag "pet[name]", nil, placeholder: "pet2", class: "pet2" %>
        <%= submit_tag "Add Client"%>
      <% end %>
    </div>
    <% if @clients.size >= 1 %>
      <% @clients.each do |p| %>
        <div class="">
          <% if p.pet %>
            <h3 class="pet">Pet: <%= link_to p.pet.name, "/pet/#{p.pet.id}", class: "pet" %>  </h3>
            <a class="little-button"><%= link_to "Create Report", "/report/#{p.pet.id}", class:"little" %> </a>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
    <div class="side-image-content">
      <h4></h4>
      <h1><span class="pet-name"></span></h1>
      <a class="create-report" href=""></a>
      <div class="owner-info">
        <div class="left">
          <h4><span class="owner-name"></span></h4>
          <h4><span class="owner-email"></span></h4>
          <h4><span class="owner-phone"></span></h4>
        </div>
        <img class="pet-photo" src=""></h4>
      </div>

      <div class= "reportcard">



      </div>
    </div>

  </div>
</div>


<% end %>

<% if current_user.user_roles.include?("owner")%>
  <div class= "ownerpage">
    <a class="add-pet">Add Pet</a>
    <h3 class="show-form" style="display: none" >
      <%= form_tag "/new-pet", multipart: true do %>
        <input type="hidden" name="pet[owner_id]" value="<%= current_user.id %>" />
        <%= text_field_tag "pet[name]", nil, placeholder: "name", class: "name", :required => true  %>
        <br>
        <%= text_field_tag "pet[breed]", nil, placeholder: "breed", class: "breed", :required => true  %>
        <br>
        <%= text_field_tag "pet[color]", nil, placeholder: "color", class: "color", :required => true  %>
        <br>
        <%= label_tag "Upload Photo" %>
        <%= file_field_tag "pet[picture]" %>
        <%= submit_tag "Add Pet" %>
      <%end%>
    </h3>
    <div class="my-pets">
      <h2>My Pets</h2>
      <% @pets.each do |p|%>
        <h3 class="pet2"><%= p.name%> </h3>
      <% end %>

    <div class="my-sitters">
      <h2>My Sitters</h2>
      <%= link_to "Find New Sitter", "/sitters" %>
        <% if @my_sitters %>
          <% @my_sitters.each do |s| %>
          <div>
              <%= link_to "#{s.sitter.name}", "/sitter-profile/#{s.sitter.id}" %>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>


    <% if @pets.count > 1 %>
      <div class= "dboards">
        <% @pets.in_groups_of(2, false).each do |group| %>
        <div class="animals">
          <% group.each do |pet| %>
            <div class="sitter-row">
              <h3 class ="p-name">Dashboard for <%= pet.name %> </h3>
              <div class="petpic"><%= image_tag pet.picture.url(:profile) %> </div>
              <div class= "reportcard">
                <% pet.reports.reverse.each do|r| %>
                <div class= "individual">
                  <h2>Report for <%= r.created_at.strftime("%A, %b %d") %> </h2>
                  <p>Sitter: <%= link_to "#{r.sitter.name}", "/sitter-profile/#{r.sitter.id}"  %> </p>
                  <div class= "activity">
                    <p> <%= r.pet.name %> spent a large part of the day <%= r.activity %>. The day was filled with lots of excitement and <%= r.pet.name %> was <%= r.emotion %> most of the day.</p>
                  </div>
                  <div class= "images">
                    <% r.images.each do |i| %>
                      <%= image_tag i.image_url.url(:image) %>
                    <% end  %>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>
    <% else %>
    <div class= "dboards">
    <% @pets.each do |p| %>
    <div class="animals">
      <div class= "animal-info">
        <h3 class="p-name">Dashboard for <%= p.name %> </h3>
        <div class="petpic"><%= image_tag p.picture.url(:profile) %> </div>
      </div>
          <div class= "reportcard">
            <% p.reports.reverse.each do|r| %>
            <div class= "individual">
              <h2>Report for <%= r.created_at.strftime("%A, %b %d") %> </h2>
              <p>Sitter: <%= link_to "#{r.sitter.name}", "/sitter-profile/#{r.sitter.id}"  %> </p>
              <div class= "activity">
                <p> <%= r.pet.name %> spent a large part of the day <%= r.activity %>. The day was filled with lots of excitement and <%= r.pet.name %> was <%= r.emotion %> most of the day.</p>
              </div>
              <div class= "images">
                <% r.images.each do |i| %>
                  <%= image_tag i.image_url.url(:image) %>
                <% end  %>
              </div>
            </div>
            <% end %>
          </div>
      <% end %>
    <% end %>
    </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1 class="title">Welcome to the Yappy Trails Club!</h1>


<div class= "user-type">
  <div class= "owner">
    <h2><%= link_to "I am a pet owner", new_owner_path %></h2>
  </div>
  <div class= "sitter">
    <h2><%= link_to "I am a pet sitter", new_sitter_path %></h2>
  </div>
</div>


<!-- .button a {
    display: block;
    width: 100%;
    height: 100%;
} -->

app/views/users/new_owner.html.erb
<div class="sign-up">

  <h1>Sign Up</h1>

  <%= form_tag "/new-owner", class:"sitter-form" do %>
    <input type="hidden" name="role[role]" value="owner"/>
    <%= render partial: "new_user_form" %>
  <%end%>
  <div class="sign-in">Already have an account?<span><%= link_to "Sign In", "/user-sign-in" %></span></div>

</div>

app/views/users/new_sitter.html.erb
<div class="sign-up">

  <h1>Sign Up</h1>

  <%= form_tag "/new-sitter", class:"sitter-form" do %>
    <input type="hidden" name="role[role]" value="sitter"/>
    <%= render partial: "new_user_form" %>
  <%end%>
  <div class="sign-in">Already have an account?<span><%= link_to "Sign In", "/user-sign-in" %></span></div>

</div>

app/views/users/sign_in.html.erb
<% if !@current_user %>
  <div class="sign-in">
    <h1 class="in">Sign In</h1>
    <%= form_tag sign_in_path, class:"navbar-form" do %>
      <input type="email" name="email" placeholder="Email" class="form-control">
      <br>
      <input type="password" name="password" placeholder="Password" class="form-control">
      <br>
      <input type="submit" value="Sign In">
      <br>
    <% end %>
    <div class="sign-up">Don't have an account yet? <span><%= link_to "Sign Up", :new_owner %></span></div>
  </div>
<% end %>

app/views/users/sign_out.html.erb
<h2><%= link_to "Sign Out", sign_out_path %></h2>

app/views/users/sitter_profile.html.erb
<div class="profile">
  <h2><%= @sitter.name %></h2>
  <h3><%= @sitter.email %></h3>
  <% if @sitter.picture != nil %>
    <%= image_tag @sitter.picture.url(:square), class:"sitter-round" %>
  <% else %>
    <%= image_tag "pna.png" %>
  <% end %>
  <h3><%= number_to_phone(@sitter.phone)%></h3>
  <h3>About <%= @sitter.name %></h3>
     <p><%= @sitter.bio %></p>

  <% if current_user == @sitter %>
  <a class="show">Edit Profile</a>
    <div class= "update" style="display:none">
      <%= form_tag "/edit-sitter/#{@sitter.id}", multipart: true  do %>
        <%= text_field_tag "user[bio]", nil, placeholder: "bio", class: "bio", :required => true  %>
      <br>
        <%= label_tag "Change Image" %>
        <%= file_field_tag "user[picture]" %>
      <br>
        <%= submit_tag "Update Profile" %>
      <%end%>
    </div>
  <% else %>
    <h2><%= form_tag "/select-sitter/#{@sitter.id}" %> </h2>
    <%= submit_tag "Select #{@sitter.name} as your sitter" %>
  <% end %>
</div>

app/views/users/sitters.html.erb
<h2>Available sitters</h2>

<% if @sitters.count > 0 %>
  <% @sitters.in_groups_of(4, false).each do |group| %>
  <div class="row">
    <% group.each do |s| %>
    <div class="sitter-row">
      <%= link_to "#{s.user.name}", "/sitter-profile/#{s.user.id}" %>
      <h2><%= s.user.name %></h2>
      <!-- <h3><%= s.user.email %></h3> -->
      <!-- <%= image_tag "pna.png" %> -->
      <% if s.user.picture.url != nil %>
        <%= image_tag s.user.picture.url:square, class:"sitter-round" %>

      <% else %>
        <%= image_tag "pna.png" %>
      <% end %>
      <!-- <h3><%= number_to_phone(s.user.phone) %></h3> -->
      <h3>About <%= s.user.name %></h3>
      <p><%= s.user.bio %></p>
      <h2><%= form_tag "/select-sitter/#{s.user.id}" %> </h2>
      <%= submit_tag "Select #{s.user.name} as your sitter" %>
    </div>
      <% end %>
  </div>
  <% end %>
<% end %>