config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  get "/new-owner", to: "users#new_owner", as: :new_owner
  get "/new-sitter", to: "users#new_sitter", as: :new_sitter
  get "/user-sign-in", to: "users#sign_in"
  post "/new-owner", to: "users#owner_create"
  post "/new-sitter", to: "users#sitter_create"
  get "/account/:id", to: "users#account", as: :account
  get "/sitter-profile/:id", to: "users#sitter_profile"
  get "/sitter-profile/:id/edit", to:"users#edit_sitter"
  post "/edit-sitter/:id", to:"users#update_sitter_profile"
  get "/sitters", to: "users#sitters"
  post "/select-sitter/:id", to: "users#select_sitter"

  get "/new-client", to: "users#new_client"
  post "/new-client", to: "users#new_client"

  post "/sign-in", to: "sessions#sign_in", as: :sign_in
  get "/sign-out", to: "sessions#sign_out", as: :sign_out

  get "/new-pet", to: "pets#new", as: :new_pet
  post "/new-pet", to: "pets#create"
  get "/report/:id", to: "pets#report", as: :report
  post "/report/:id", to: "reports#create_report"

  get "/images", to: "instagram#show"

  get "/pet/:id", to: "pets#show"

  get "yappytrailsclub/about", to: "reports#about", as: :about

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_url, ImageUploader
  belongs_to :report
  belongs_to :pet
  belongs_to :user


  def square_image
    image_url.url(:image)
  end

  def profile_image
    picture.picture.url(:profile)
  end

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :owner, class_name: "User"
  has_many :reports
  has_many :sitter_records
  has_many :images
  mount_uploader :picture, ImageUploader
  validates :picture, presence: true
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :images
  belongs_to :sitter, class_name: "User"
  belongs_to :owner, class_name: "User"
  belongs_to :pet
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/sitter_record.rb
class SitterRecord < ActiveRecord::Base
  belongs_to :sitter, class_name: "User"
  belongs_to :pet
  validates  :pet_id, uniqueness: {scope: :sitter_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  has_many :roles
  has_secure_password validations: false
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :sitter_records
  validates :password, confirmation: true, presence: true, if: :needs_password?
  validates :username, presence: true, if: :registered
  mount_uploader :picture, ImageUploader




  def user_roles
    roles=[]
    self.roles.each do |r|
      roles << r.role
    end
    return roles
  end

  def registered
    if self.roles.where("role=? or role=?", "sitter", "owner").count > 0
      true
    end
  end

  def needs_password?
    if new_record? && registered
      true
    end

  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController

  def show

    @popular = Instagram.media_popular
  end


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
  end

  def report
    @pet = Pet.find_by(id: params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
    # @pet.picture = params[:pet][:picture]
    if @pet.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/new-owner", notice: @pet.errors
    end

  end



  def show
    @pet = Pet.find_by(id: params[:id])

    @sitter_ids = []
    @images = []
    @pet.reports.each do |i|
      i.images.each do |p|
        @images << p.image_url
      end
    end
    @pet.sitter_records.each do |r|
      @sitter_ids << r.sitter_id
    end
    render :json=> {
      pet: @pet,
      owner: @pet.owner,
      reports: @pet.reports.as_json(include: {images: {methods: :square_image} } )
      }
  end

  def profile
    @pet = Pet.find_by(id: params[:id])
  end


  private

  def pet_params
    params.require(:pet).permit(:picture, :owner_id, :name, :breed, :color, :sitter_id)
  end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController


  def create_report
    @report = Report.new(report_params)
    @report.save
    if @report.save
      @image= Image.new(image_url: params[:image][:image_url], report_id: @report.id)
      @image.save
    end
    @client = Twilio::REST::Client.new
    @client.messages.create(from: '+12064880825', to: "+1#{@report.pet.owner.phone}", body: "Login to YappyTrails.club to see #{@report.pet.name}'s full report card!", media_url: "#{@image.image_url.url}")
    ReportMailer.new_report(@report.id).deliver_now
    redirect_to "/account/#{@current_user.id}"
  end

  def about
  end


  private

  def report_params
    params.require(:report).permit(:owner_id, :sitter_id, :pet_id, :activity, :emotion)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def sign_out
    session.delete(:user_id)
    redirect_to "/", notice: "You have been signed out"
  end

  def sign_in
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/account/#{@user.id}", notice: "You have been signed in"
    else
      redirect_to "/", notice: "Wrong username/password. Try again."
    end
  end

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'

class TwilioController < ApplicationController



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :bio

  def index

  end

  def new_client
    @user = User.new(user_params)
    if @user.save
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      @pet =  Pet.new(name: params[:pet][:name], owner_id: @user.id)
      @pet.save
      @sitter_record = SitterRecord.new(pet_id: @pet.id, owner_id: @user_id, sitter_id: @current_user.id)
      @sitter_record.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/new-owner", notice: "New client did not save"
    end
  end

  def owner_create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      redirect_to "/new-pet"
    else
      redirect_to "/new-owner", notice: "Username or email not complete, or passwords do not match."
    end
  end

  def sitter_create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @role = Role.new(role: (params[:role][:role]), user_id: @user.id)
      @role.save
      redirect_to "/sitter-profile/#{@user.id}"
    else
      redirect_to "/new-sitter", notice: "Username or email not complete, or passwords do not match."
    end
  end

  def new_sitter
  end

  def account
    @pets = Pet.where(owner_id: @current_user.id)
    @clients = SitterRecord.where(sitter_id: @current_user.id)
    @sitter_records = SitterRecord.where(owner_id: @current_user.id)
    @my_sitters = []
    @sitter_records.each do |s|
      @my_sitters << s unless @my_sitters.include?(s.sitter_id)
    end
  end

  def sitter_profile
    @sitter = User.find(params[:id])
  end

  def update_sitter_profile
    @update = User.find(params[:id])
    @update.bio = params[:user][:bio]
    @update.picture = params[:user][:picture]
    @update.save
    if @update.save
      redirect_to "/account/#{@current_user.id}"
    else
      redirect_to "/sitter-profile/#{@current_user.id}/edit", notice: "Update not saved."
    end
  end

  def edit_sitter
    @sitter = User.find(params[:id])
  end

  def sitters
    @sitters = Role.where(role: "sitter")
  end

  def select_sitter
    @pets = Pet.where(owner_id: @current_user.id)
    @sitter = User.find(params[:id])
    @pets.each do |p|
      SitterRecord.create(sitter_id: @sitter.id, owner_id: @current_user.id, pet_id: p.id)
    end
    redirect_to "/account/#{@current_user.id}"
  end



  private

  def user_params
    params.require(:user).permit(:bio, :email, :password, :phone, :username, :name, :role, :current_city, :password_confirmation, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    current_user = @current_user
  end


  def gravatar_for(email)
    hashed_email = Digest::MD5.hexdigest(email.downcase)
    image_tag "http://www.gravatar.com/avatar/#{hashed_email}.jpg", alt: "Picture"
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yappy Trails Club</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<% if current_page?("/") %>
  <body class="background">
<% elsif current_page?("/new-sitter") %>
    <body class="background">
<% elsif current_page?("/new-owner") %>
    <body class="background">
    <% else %>
    <body>
<% end %>


<div class="wrapper-for-content-outside-of-footer">

  <div class="page-wrap">

    <header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= link_to image_tag("paws2.png"), root_path, class: "logo", alt: "Logo Image" %>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if !@current_user %>
          <li class="nav-link"><%= link_to "Sign In", "/user-sign-in" %></li>
        <% else %>

        <li class="nav-link"><%= link_to "Sign Out", sign_out_path %></li>
        <li class="nav-link"><%= link_to "My Dashboard", "/account/#{@current_user.id}" %></li>
        <% if @current_user.user_roles.include?("sitter") %>
          <li class="nav-link"><%= link_to "View My Profile", "/sitter-profile/#{@current_user.id}" %></li>
        <% end %>
      <% end %>
        <!-- <li id="js-navigation-more" class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
            <li class="more"><a href="javascript:void(0)">Item with submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                <li><a href="javascript:void(0)">Another Item</a></li>
              </ul>
            </li>
            <li class="more"><a href="javascript:void(0)">Another submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                <li><a href="javascript:void(0)">An Item</a></li>
              </ul>
            </li>
          </ul>
        </li> -->
      </ul>
    </nav>

  </div>
</header>


  <% if flash.key?(:notice) %>
    <div class = 'flash-alert'>
      <%= flash[:notice] %>
    </div>
  <% end %>


<%= yield %>

</div>
</div>

<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
    <ul>
      <li><%= link_to "About Yappy Trails Club", about_path %></li>
      <li><%= mail_to "khambro@gmail.com", "Contact" %></li>
      <!-- <li><a href="javascript:void(0)">Products</a></li> -->
    </ul>

    <!-- <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>

      <ul class="footer-social">
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
          </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
        </a></li>
      </ul>
    </div> -->
</footer>



<!-- <footer class="footer" role="contentinfo">
    <ul>
      <li><%= link_to "About Yappy Trails Club", about_path %></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
</footer> -->





</body>
</html>

app/views/shared/_new_pet.html.erb
<div class="new-pet">

  <h1>Create a Pet Profile!</h1>

  <!-- this logic nees to be fixed. Doesn't work if someone is owner AND sitter -->
  <%= form_tag "/new-pet" do %>
    <% if current_user.roles.include?("owner") %>
      <input type="hidden" name="pet[owner_id]" value="<%= current_user.id %>" />
    <% elsif current_user.roles.include?("sitter") %>
      <input type="hidden" name="pet[owner_id]" value="<%= current_user.id %>" />
    <% else %>
      <input type="hidden" name="pet[unregistered_id]" value="<%= current_user.id %>" />
    <%end%>
    <%= text_field_tag "pet[name]", nil, placeholder: "name", class: "name", :required => true  %>
    <br>
    <%= text_field_tag "pet[breed]", nil, placeholder: "breed", class: "breed", :required => true  %>
    <br>
    <%= text_field_tag "pet[color]", nil, placeholder: "color", class: "color", :required => true  %>
    <br>

    <%= submit_tag %>
  <%end%>

</div>